Add type
digitalbazaar/bedrock-web-local-vc-store pull request #9
Opened 2021-07-29 16:56 UTC by JoshDunnDev

2021-07-29 17:13 UTC, dlongley requested changes

2021-07-29 17:13 UTC, dlongley commented on lib/LocalVerifiableCredentialStore.js
> +          'content.type'
I have all the same concerns here about indexing again. I see that the find function allows for `parentId` to be omitted and `type` to be present, for example. That would not result in the index being used properly.

What are the queries that are meant to be supported here? Which fields will be present? The indexes must match those fields. If we need another index for the queries we need to support we should add it.

2021-07-29 20:17 UTC, dlongley approved these changes
So, I think this addresses the issue I raised before. But what happens if both `type` and `parentId` are passed? I think the caller would be confused by the outcome.

It seems like that should either still work properly -- or an exception should be thrown if it isn't supported. If it is supported, it doesn't necessarily mean a new index is needed (unless I don't understand how pouchDB works) -- you should just make it pick whichever you think would be sufficient in that situation.

If you want to defer solving this with an issue, please file one. I'm going to approve for now to keep things going. Thanks!

2021-07-29 21:35 UTC, JoshDunnDev commented
> So, I think this addresses the issue I raised before. But what happens if both `type` and `parentId` are passed? I think the caller would be confused by the outcome.
> 
> It seems like that should either still work properly -- or an exception should be thrown if it isn't supported. If it is supported, it doesn't necessarily mean a new index is needed (unless I don't understand how pouchDB works) -- you should just make it pick whichever you think would be sufficient in that situation.
> 
> If you want to defer solving this with an issue, please file one. I'm going to approve for now to keep things going. Thanks!

@dlongley So right now there is no reason we need to call `type` and `parentId` at the same time, however this may not always be the case. I was trying to consolidate the indexing so we don't have to create a separate index for every case. We cannot include `content.type` and `meta.parentId` together because not every record includes `meta.parentId`. Since every record does not have `meta.parentId`, trying to index them together causes `meta.parentId` to be an in-memory field. I am not really sure how to get around this effectively when calling those together.

2021-07-30 17:38 UTC, dmitrizagidulin approved these changes
:+1:

2021-07-30 17:38 UTC, merged

2021-07-30 23:35 UTC, dlongley commented
@JoshDunnDev,

My point was that if calling the function with both `type` and `parentId` is illegal -- we should check for that condition and throw an error. Otherwise, someone may call it with both and just get back something that doesn't match `parentId` and be confused.